export { default as ingeniaProject } from "./ingenia.jpg"
export { default as timbringProject } from "./timbring.jpg"
export { default as countriesProject } from "./countries.jpg"
export { default as cardQRProject } from "./CardQR.png"
export { default as pokedexProject } from "./Pokedesk.png"